# Generated by Django 5.1.4 on 2026-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('yoga', 'Yoga'), ('hiit', 'HIIT'), ('pilates', 'Pilates'), ('zumba', 'Zumba'), ('crossfit', 'CrossFit'), ('cardio', 'Cardio'), ('musculation', 'Musculation'), ('boxe', 'Boxe'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('level', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous', 'Tous niveaux')], default='tous', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('location', models.CharField(default='Salle principale', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('waiting', "Liste d'attente")], default='confirmed', max_length=15)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
    ]
